typography_spectrum: 0.3562778071500361
content_rating:
  adult: false
color:
  saturation: 0.4920416825916618
  brandStrength: 0.6837686735671014
  lightness: 0.31960904179140925
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  rhythmicContrast: 0.4773869893979281
layout_spectrum: 0.003858469193801284
author:
  email: holger.milde@gmail.com
  name: Holger Milde
  url: 'https://about.me/ecopunk'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0881cd4f-1b3d-4fb2-be79-ec31a5173d6c.jpg
name: Ecopunk
navigation:
  - name: Meine Flipboard Magazine
    url: 'https://flipboard.com/@ecopunk'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a6d79164-8e5b-44c6-b8d9-73b8cf02d554.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Digital kuratierender Romantiker
