author:
  email: holger.milde@gmail.com
content_rating:
  adult: false
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4258862
  brandStrength: 0.2497315
  lightness: 1
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  rhythmicContrast: 0.6965628
typography_spectrum: 0.1723953
layout_spectrum: 0.1960257
name: ecopunk
