name: Holger Milde
navigation:
  - name: Xing
    url: 'https://www.xing.com/profile/Holger_Milde'
    type: external
  - name: Flipboard
    url: 'https://flipboard.com/@ecopunk'
    type: external
  - name: Pinterest
    url: 'https://de.pinterest.com/ecopunk/'
    type: external
  - name: Strava
    url: 'https://www.strava.com/athletes/ecopunk'
    type: external
  - name: Impressum
    id: 9a158c84-58e4-4ba5-944c-d7f7f27fa57c
    type: content
content: []
description: >-
  Technologieverliebt. Vater einer wundervollen Tochter. Liebe, lebe und laufe
  in Hamburg und Westersode, höre elektronische Musik und mag den #fcsp
author:
  email: holger.milde@gmail.com
  name: Holger Milde
  url: 'https://about.me/ecopunk'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.5339412189404121
color:
  saturation: 0.6030494089800827
  brandStrength: 0.2354715514588769
  rhythmicContrast: 0.7423745677599887
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
  lightness: 0.1272084504875843
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a506a71b-fb10-4d30-aad4-df10dcfcbabb.png
github: true
title: Digital kuratierender Romantiker
purpose:
  - type: contact
    url: 'tel:+491711979003'
    label: Call +491711979003
  - type: contact
    url: 'mailto:holger.milde@gmail.com'
    label: Contact me
content_rating:
  adult: false
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a6d79164-8e5b-44c6-b8d9-73b8cf02d554.png
typography_spectrum: 0.002936214201687143
analytics:
  google: UA-83695144-1
