typography_spectrum: 0.1723953
content_rating:
  adult: false
color:
  saturation: 0.4258862
  brandStrength: 0.1852846
  lightness: 1
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  rhythmicContrast: 0.6965628
layout_spectrum: 0.2658432
author:
  email: holger.milde@gmail.com
name: ecopunk
navigation:
  - name: Meine Flipboard Magazine
    url: 'https://flipboard.com/@ecopunk'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
